/* Automatically generated by './build/bin/build-entry.js' */

import Button from '../packages/button/index.js';
import Drag from '../packages/drag/index.js';
import Grid from '../packages/grid/index.js';
import Input from '../packages/input/index.js';
import Test from '../packages/test/index.js';
import Video from '../packages/video/index.js';
const components = [
  Button,
  Drag,
  Grid,
  Input,
  Test,
  Video,
];

const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });

  Vue.prototype.$ELEMENT = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };
  
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  install,
  Button,
  Drag,
  Grid,
  Input,
  Test,
  Video
};
