
    export default [
      {path: "/", redirect: "/wrui"},
      {
        path:"/wrui",
        redirect:"/wrui/guide",
      },
      {
        path:"/wrui/guide",
        component:()=>import("@/docs/guide.md")
      }
      ,
      {
      path:"/wrui/basic",
      redirect:"/wrui/basic/button",
      component:()=>import("@/components/wrui-middle-router.vue"),
      children:[
        {
      path:"button",
      component:()=>import('@/docs/button.md')
    }
    ,
{
      path:"container",
      component:()=>import('@/docs/container.md')
    }
    ,
{
      path:"icon",
      component:()=>import('@/docs/icon.md')
    }
    
      ],
    }  
    ,
{
      path:"/wrui/data",
      redirect:"/wrui/data/tag",
      component:()=>import("@/components/wrui-middle-router.vue"),
      children:[
        {
      path:"tag",
      component:()=>import('@/docs/tag.md')
    }
    ,
{
      path:"tree",
      component:()=>import('@/docs/tree.md')
    }
    ,
{
      path:"table",
      component:()=>import('@/docs/table.md')
    }
    ,
{
      path:"progress",
      component:()=>import('@/docs/progress.md')
    }
    ,
{
      path:"badge",
      component:()=>import('@/docs/badge.md')
    }
    
      ],
    }  
    ,
{
      path:"/wrui/form",
      redirect:"/wrui/form/radio",
      component:()=>import("@/components/wrui-middle-router.vue"),
      children:[
        {
      path:"radio",
      component:()=>import('@/docs/radio.md')
    }
    ,
{
      path:"checkbox",
      component:()=>import('@/docs/checkbox.md')
    }
    ,
{
      path:"select",
      component:()=>import('@/docs/select.md')
    }
    ,
{
      path:"dropdown",
      component:()=>import('@/docs/dropdown.md')
    }
    ,
{
      path:"input",
      component:()=>import('@/docs/input.md')
    }
    
      ],
    }  
    ,
{
      path:"/wrui/notice",
      redirect:"/wrui/notice/notify",
      component:()=>import("@/components/wrui-middle-router.vue"),
      children:[
        {
      path:"notify",
      component:()=>import('@/docs/notify.md')
    }
    
      ],
    }  
    ,
{
      path:"/wrui/ohter",
      redirect:"/wrui/ohter/video",
      component:()=>import("@/components/wrui-middle-router.vue"),
      children:[
        {
      path:"video",
      component:()=>import('@/docs/video.md')
    }
    ,
{
      path:"drag",
      component:()=>import('@/docs/drag.md')
    }
    ,
{
      path:"test",
      component:()=>import('@/docs/test.md')
    }
    
      ],
    }  
    
    ]
  